server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

application:
  security:
    jwt:
      secret-key: KoNBlgUHCn24kEKj0ubb/GQebGqQjqOPDhTr/hICxbQ=

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: channel-service
              uri: lb://CHANNEL-SERVICE
              predicates:
                - Path=/channels/**