server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_auth
    username: streaming
    password: streaming123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info