spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_media
    username: streaming
    password: streaming123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true