server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_media
    username: streaming
    password: streaming123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

application:
  media:
    allowed-image-types:
      - image/jpeg
      - image/png
      - image/webp

    limits:
      avatar-max-size: 5MB
      banner-max-size: 10MB
      stream-thumbnail-max-size: 10MB
