server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_users
    username: streaming
    password: streaming123

  jpa:
    properties:
      jakarta.persistence.bean.manager: org.springframework.orm.jpa.support.ExecutingBeanManager

    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
