server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_users
    username: streaming
    password: streaming123

management:
  endpoints:
    web:
      exposure:
        include: health,info